POST http://localhost:8080/api/v1/room/674f4d7002cd8e33cb0f0131/book
Content-Type: application/json

{
  "numPersons": 2,
  "From": "2024-12-25T12:00:00Z",
  "To": "2024-12-29T12:00:00Z"
}

###
GET http://localhost:8080/api/v1/booking/675698a49fdbae37e3898ac7/cancel

###
GET http://localhost:8080/api/v1/booking
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY0MTY0NzUsInJvbGUiOiJndWVzdCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VyX2lkIjoiNjc3Zjc2ZTJjZDIxODgzMjFiNzk4MjhlIn0.7ANclVY7otgnStvYeyQfoRGIuDg9ZM9Jl3btPbbtEzU


###
GET http://localhost:8080/api/v1/rooms
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY0MTY0NzUsInJvbGUiOiJndWVzdCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VyX2lkIjoiNjc3Zjc2ZTJjZDIxODgzMjFiNzk4MjhlIn0.7ANclVY7otgnStvYeyQfoRGIuDg9ZM9Jl3btPbbtEzU

###
GET http://localhost:8080/api/v1/booking/674f53dd08c9cc9be7e56f08

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "email" : "mat@foo.com",
  "password": "foobarbaz",
  "firstName": "Mateusz",
  "lastName": "Urban"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email" : "mat@foo.com",
  "password": "foobarbaz"
}

###
PUT localhost:8080/api/v1/user/677f76e2cd2188321b79828e
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY0MTgyMDEsInJvbGUiOiJndWVzdCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VyX2lkIjoiNjc3Zjc2ZTJjZDIxODgzMjFiNzk4MjhlIn0.qt7PeHktFq1yL9b3ie4ifk8y116Jih6-JZjDaPsxuAI

{
  "firstName": "jeden",
  "lastName": "trzy"
}


###
POST http://localhost:8080/api/v1/hotel/6746e85e55ee8ee644830b5e
Content-Type: application/json

{
  "id": "6746e85e55ee8ee644830b5e",
  "name": "Bellucia Hotel",
  "location": "France",
  "rooms": [
    "6746e85e55ee8ee644830b5f",
    "6746e85e55ee8ee644830b60",
    "6746e85e55ee8ee644830b61"
  ],
  "rating": 3
}


###
### GET request to example server
GET http://localhost:8080/api/v1/hotels
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY0MTY0NzUsInJvbGUiOiJndWVzdCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VyX2lkIjoiNjc3Zjc2ZTJjZDIxODgzMjFiNzk4MjhlIn0.7ANclVY7otgnStvYeyQfoRGIuDg9ZM9Jl3btPbbtEzU
###

### GET request to example server
GET http://localhost:8080/api/v1/admin/users
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY0MTY0NzUsInJvbGUiOiJndWVzdCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VyX2lkIjoiNjc3Zjc2ZTJjZDIxODgzMjFiNzk4MjhlIn0.7ANclVY7otgnStvYeyQfoRGIuDg9ZM9Jl3btPbbtEzU

###


