POST http://localhost:8080/api/v1/room/67489660df9fc9c02cb271ed
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzMxNTQ5NzUsImlkIjoiNjc0ZDliMzlhMzVkNzk0YTNkZTgyZWU2In0.Ul_W3HrCm_BEI0zJA-wCuxtNmg-f5CRMkSnkCMnxPhQ
Content-Type: application/json

{
  "numPersons": 2,
  "From": "2024-12-24T12:00:00Z",
  "To": "2024-12-26T12:00:00Z"
}

###
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "email" : "jon@foo.com",
  "password": "foobarbaz",
  "firstName": "James",
  "lastName": "Bar"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email" : "james@bar.com",
  "password": "supersecurepassword"
}

###
POST http://localhost:8080/api/v1/hotel/6746e85e55ee8ee644830b5e
Content-Type: application/json

{
  "id": "6746e85e55ee8ee644830b5e",
  "name": "Bellucia Hotel",
  "location": "France",
  "rooms": [
    "6746e85e55ee8ee644830b5f",
    "6746e85e55ee8ee644830b60",
    "6746e85e55ee8ee644830b61"
  ],
  "rating": 3
}


###
### GET request to example server
GET http://localhost:8080/api/v1/hotels
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzI4OTEwMjksImlkIjoiNjc0ODk2NjBkZjlmYzljMDJjYjI3MWY0In0.nVMgtl7O1S-0mRk6cAPLk7ZgCDVh_Lal6BF1iyLOSCE
###



