POST http://localhost:8080/api/v1/room/674f4d7002cd8e33cb0f0131/book
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3NDI1OTIsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6ImFkbWluIn0.SfkYinaIGT9ac1ft7QfkNgpcNJyjmcwyKnYh9NfFVMU
Content-Type: application/json

{
  "numPersons": 2,
  "From": "2024-12-25T12:00:00Z",
  "To": "2024-12-29T12:00:00Z"
}

###
GET http://localhost:8080/api/v1/booking/675698a49fdbae37e3898ac7/cancel
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3NDI1OTIsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6ImFkbWluIn0.SfkYinaIGT9ac1ft7QfkNgpcNJyjmcwyKnYh9NfFVMU

###
GET http://localhost:8080/api/v1/booking
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3NDI1OTIsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6ImFkbWluIn0.SfkYinaIGT9ac1ft7QfkNgpcNJyjmcwyKnYh9NfFVMU

###
GET http://localhost:8080/api/v1/rooms
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3NDI1OTIsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6ImFkbWluIn0.SfkYinaIGT9ac1ft7QfkNgpcNJyjmcwyKnYh9NfFVMU

###
GET http://localhost:8080/api/v1/booking/674f53dd08c9cc9be7e56f08
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3NDI1OTIsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6ImFkbWluIn0.SfkYinaIGT9ac1ft7QfkNgpcNJyjmcwyKnYh9NfFVMU

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "email" : "mat@foo.com",
  "password": "foobarbaz",
  "firstName": "Mateusz",
  "lastName": "Urban"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email" : "mat@foo.com",
  "password": "foobarbaz"
}

###
PUT localhost:8080/api/v1/user/677f76e2cd2188321b79828e
Content-Type: application/json
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdEBmb28uY29tIiwiZXhwIjoxNzM2NDIxMTcxLCJpZCI6IjY3N2Y3NmUyY2QyMTg4MzIxYjc5ODI4ZSIsInJvbGUiOiJndWVzdCJ9.qtVPropUiqdWDFZ0gonDVbdI0TK_mweWSdUXJGWdX98

{
  "firstName": "sadsadasd",
  "lastName": "dupa"
}


###
POST http://localhost:8080/api/v1/hotel/6746e85e55ee8ee644830b5e
Content-Type: application/json
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdEBmb28uY29tIiwiZXhwIjoxNzM2NDIxMTcxLCJpZCI6IjY3N2Y3NmUyY2QyMTg4MzIxYjc5ODI4ZSIsInJvbGUiOiJndWVzdCJ9.qtVPropUiqdWDFZ0gonDVbdI0TK_mweWSdUXJGWdX98

{
  "id": "6746e85e55ee8ee644830b5e",
  "name": "Bellucia Hotel",
  "location": "France",
  "rooms": [
    "6746e85e55ee8ee644830b5f",
    "6746e85e55ee8ee644830b60",
    "6746e85e55ee8ee644830b61"
  ],
  "rating": 3
}


###
### GET request to example server
GET http://localhost:8080/api/v1/hotels
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJhci5jb20iLCJleHAiOjE3MzM3Mzg1MzUsImlkIjoiNjc0ZjRkNzAwMmNkOGUzM2NiMGYwMTNjIiwicm9sZSI6Imd1ZXN0In0.uUKA44HcWoM112Lufx5D4tRkkwvo-Ks-UnRqDZowFjI
###

### GET request to example server
GET http://localhost:8080/api/v1/admin/users
X-API-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdEBmb28uY29tIiwiZXhwIjoxNzM2NDIxMTcxLCJpZCI6IjY3N2Y3NmUyY2QyMTg4MzIxYjc5ODI4ZSIsInJvbGUiOiJndWVzdCJ9.qtVPropUiqdWDFZ0gonDVbdI0TK_mweWSdUXJGWdX98
###


